name: Master merge checks

on:
  pull_request:
    branches:
      - master

jobs:
  check_head_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check head branch
        run: |
          BRANCH_NAME="${{ github.head_ref }}"

          echo "Branch name is: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == repo/*  || 
                "$BRANCH_NAME" == docs/*  || 
                "$BRANCH_NAME" == bug/*   ||
                "$BRANCH_NAME" == devel/* ||
                "$BRANCH_NAME" == feature/* ]]; then
            echo "‚ùå Branch name does not start with 'private/'."
            echo "This workflow only runs on branches starting with 'private/'."
            exit 1
          fi