name: CI (local)

on:
  pull_request:
    branches:
      - master

jobs:
  repo_check:
    permissions:
      actions: write
    uses: Tai-Min/Robo-Bus/.github/workflows/local_runner_commiter_check.yml@private/local-runner-test
    with:
      repo: Tai-Min/Robo-Bus
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      repo_token: ${{ secrets.GITHUB_TOKEN }}

  hardware_tests:
    runs-on: ubuntu-latest
    needs: repo_check
    if: needs.repo_check.outputs.association == 0
    steps:
      - run: echo "Hello tests!"