# Use local runner to run tests on a real hardware
name: CI (local)

on:
  pull_request:
    branches-ignore:
      - private/**

jobs:
  # Committer must be a collaborator to use a local runner
  committer_check:
    permissions:
      actions: write
    uses: Tai-Min/Robo-Bus/.github/workflows/committer_check.yml@master
    with:
      repo: Tai-Min/Robo-Bus
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      repo_token: ${{ secrets.GITHUB_TOKEN }}

  filter:
    runs-on: ubuntu-latest
    outputs:
      fw: ${{ steps.filter.outputs.fw }}
    needs: committer_check
    if: needs.committer_check.outputs.association == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            fw:
              - 'fw/**'

  # Do stuff here later...
  hardware_tests:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.fw == 'true'
    steps:
      - name: Run hardware tests
        run: echo "Hello tests!"