# Use local runner to run tests on a real hardware
name: CI (local)

on:
  pull_request:
    types: [ labeled ]
    branches-ignore:
      - private/**

jobs:
  hardware_tests:
    if: ${{ github.event.label.name == 'run_tests' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            fw:
              - 'fw/**'

      - name: Run hardware tests
        if: steps.committer_check.outputs.association == 'true'
        run: echo "Hello tests!"