# Use local runner to run tests on real hardware
name: CI (local)

on:
  pull_request:
    branches:
      - master

jobs:
  user_check:
    permissions:
      actions: write
    uses: Tai-Min/Robo-Bus/.github/workflows/local_runner_committer_check.yml@master
    with:
      repo: Tai-Min/Robo-Bus
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      repo_token: ${{ secrets.GITHUB_TOKEN }}

  hardware_tests:
    runs-on: ubuntu-latest
    needs: user_check
    if: needs.user_check.outputs.association == 0
    steps:
      - run: echo "Hello tests!"