name: PR check

on:
  pull_request_target:

jobs:
  workflows_check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0

    - name: Check changes in .github folder
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          gh:
            - '.github/**'

    - name: Committer check
      if: steps.filter.outputs.gh == 'true'
      id: committer_check
      uses: Tai-Min/Robo-Bus/.github/actions/committer_check@master
      with:
        repo: Tai-Min/Robo-Bus
        pr_number: ${{ github.event.pull_request.number }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Post comment if .github folder was edited by an outsider
      if: steps.committer_check.outputs.association == 'false'
      uses: actions/github-script@v7
      with:
        script: |
          const body = `
          ⚠️ .github folder was edited by an outsider.
          ⚠️ MAKE SURE TO CHECK FOR ANY SUSPICIOUS CHANGES
          `;
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          });

    - name: Fail the check
      if: steps.committer_check.outputs.association == 'false'
      run: |
        echo "Check failed due to suspicious activity"
        exit 1