name: Provide warnings for suspicious PRs

on:
  pull_request_target:

jobs:
  workflows_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        fetch-depth: 0

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          gh:
            - '.github/**'

    - name: Committer check
      if: steps.filter.outputs.gh == 'true'
      id: committer_check
      uses: Tai-Min/Robo-Bus/.github/actions/committer_check@repo/update-actions
      with:
        repo: Tai-Min/Robo-Bus
        pr_number: ${{ github.event.pull_request.number }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}