name: Remove run_tests

on:
  pull_request_target:
    types: [ labeled ]

jobs:
  remove_label:
    if: ${{ github.event.label.name == 'run_tests' }}

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Remove run_tests label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: run_tests